# Warning Changing the name of your application after it has been deployed will destroy all storage volumes and result in the loss of all persistent data.
name: "csa-robot"

# The type key defines the base container image that will be used to run the application.
type: "nodejs:10"

# Legal values for the size key are AUTO (the default), S, M, L, XL, XXL.
size: S

# Required
disk: 1024 #1G

dependencies:
  nodejs:
    pm2: "^2.0.0"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start server.js --no-daemon"
  locations:
    "/":
      root: "csa-robot"
      passthru: false
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true